### PR TITLE
Cleaning up, adjusting some demos and documentation

### PR DESCRIPTION
**Pull request by oderwat**
- solving most hlint hints (learning something by the way)
- rewrote some code mostly based on hlint suggestions
- removed (or commented out) some dead code
- fixed demos which where not working anymore
- corrected some docs (hopefully accurate enough)

P.S.: In the next step I want to move everything to stack / package.yaml based build, make the demos into true targets and start to write some tests and fixing/rearrange some of the docs.

### CODE REVIEW

**Comment by oderwat** [comment]
BTW: I added `statElems` and rewrote the `caching.hs` to check for my "findings" from #16. Maybe you can take a look at it, if it is "nearly right". I have to confess that my understanding still is very much limited and of an experimental nature.

**Comment by oderwat** [comment]
I also needed to change formatting slightly to make it compile as Haskell2010.

**Comment by oderwat** [comment]
So I was curious what happens when I enable -Wall and went all the way down into this rabbit hole, finally getting it (mostly) clean. I think I strife to follow https://kowainik.github.io/posts/2019-02-06-style-guide for our own projects and try to move TCache a bit into that direction too.

**Comment by agocorona** [comment]
Looks good. I will look at it in detail at the beginning of the next week

**Pull request merged**
